title: Kirobo Prediction Market Platform
description: Shareholders & Investor Overview - Business Plan & Financial Projections
theme: jekyll-theme-cayman
show_downloads: false

# SEO settings
author: Kirobo
twitter:
  username: kiroboio
  card: summary_large_image

# GitHub metadata
github:
  repository_url: https://github.com/kiroboio/prediction-ai-docs
  owner_url: https://github.com/kiroboio
